### ISSUE TITLE
Emoji search bar inconsistent color

### ISSUE THREAD

**Issue by RaitaroH** [style-it-themes/discord-inspired-bits-dark#10]
The emoji search bar should have the same color as the chat input right?

```css
.search-bar.search-bar-light .search-bar-inner {
    background-color: #484B52 !important;
}
```
