### ISSUE TITLE
Main page dropdowns are not themed

### ISSUE THREAD

**Issue by RaitaroH** [style-it-themes/discord-inspired-bits-dark#11]
By that I mean when you are not the main discordapp page and you have language or developers or community in the navbar.

Here's the code :wink: 
```css
	/*Dropdowns*/
	[class*="moreList"], [class*="localeList"] {
		background: var(--color-2f3136) !important;
	}
	[class*="moreList"]:hover, [class*="localeBase"]:hover {
		background: var(--color-35393e) !important;
		color: var(--color-eeeeee) !important;
	}
```
