### ISSUE TITLE
White edge in multi-dms right sidebar

### ISSUE THREAD

**Issue by RaitaroH** [style-it-themes/discord-inspired-bits-dark#12]
```css
.scroller-wrap.light .scrollbar, .scroller-wrap.light .scrollbar::after {
background-color: #2F3136 !important;
}
```
