### ISSUE TITLE
Last emoji in row gets cut off

### ISSUE THREAD

**Issue by RaitaroH** [style-it-themes/discord-inspired-bits-dark#9]
![screenshot_20180829_133431](https://user-images.githubusercontent.com/19552720/44782570-5553dd80-ab90-11e8-92fc-0f2efccd0e6c.png)

Fix:
```css
.emojiPicker-3m1S-j .scroller-3vODG7 .emojiItem-109bjA {
    width: 27px !important;  /*or 30px*/
}
```

**Comment by the-j0k3r** [comment]
Hello again.

Need to test this out a bit, last time I tried fixing it, there were unwanted side effects.

**Comment by vednoc** [comment]
I found that if you apply `display: none;` to the `.pad-29zQak` you don't need to change the width of emojis. Not sure whether or not this breaks anything else but so far in my short testing it actually fixes the "double" sidebar when you look at someone's profile.

`background: none;` will also fix it but it's currently being overwritten with a custom `background-color` so that will have to be removed first.

Markup:
```html
<div class="scrollbar-2rkZSL">
  <div class="track-1JN30G"></div>
  <div class="thumb-2JwNFC" style="height: 9px; top: 0px;"></div>
  <div class="pad-29zQak"></div>
</div>
```

Also @the-j0k3r, why is this a thing? :smile: 
```css
.scrollbar-2rkZSL .pad-29zQak {
  outline: 1px solid var(--color-2f3136) !important;
}

**Comment by RaitaroH** [comment]
Outlines in firefox ay?
Eh... I know what you mean....

**Comment by vednoc** [comment]
>Without there are white lines by the scrollbars in WIndows FF at least on both sidebars

Oh, got it. I would've never thought that to be the case.

Try this out and let me know how it works. :smiley:  
```css
.pad-29zQak {
  left: 0px !important;
  width: 0px !important;
}
```

**Comment by RaitaroH** [comment]
@vednoc It does solve the issue.

**Comment by the-j0k3r** [comment]
![screenshot from 2018-08-29 13-40-58](https://user-images.githubusercontent.com/31389848/44788173-3c97f780-ab91-11e8-8e4d-d50c8058f130.png)

That breaks this again

**Comment by RaitaroH** [comment]
I see. ¯\_(ツ)_/¯ here for me on the firefox linux version.

**Comment by vednoc** [comment]
I jumped back to my Windows OS to inspect it further. 😄 This seems to fix it and there's no need for outline or the other elements where `.pad-29zQak` is involved.

```css
  .pad-29zQak {
    width: 3px !important;
    left: -3px !important;
    background: var(--color-2f3136) !important;
  }
```
